blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentatie
    url: https://github.com/hanbedrijfskunde/ontwikkeling-theoom/tree/main/project-documents
    about: Bekijk de project documentatie
  - name: ğŸ’¬ Discussie starten
    url: https://github.com/hanbedrijfskunde/ontwikkeling-theoom/discussions
    about: Start een algemene discussie over het project
